
server:
  port: ${port} #服务端口
spring:
  application:
    name: demo-microservice-user #指定服务名
  ################mysql 属性配置#########################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    register-with-eureka: true #是否将自己注册到Eureka服务中，默认为true
    fetch-registry: true #是否从Eureka中获取注册信息，默认为true
    service-url: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone:  http://workstation:6868/eureka/,http://workstation:6869/eureka/
    eureka-server-connect-timeout-seconds: 60
    eureka-server-read-timeout-seconds: 60
  instance:
    prefer-ip-address: true  #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id
    lease-expiration-duration-in-seconds: 30 #续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds:  10 # 续约到期时间（默认90秒）

# actuator配置
management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点 默认是info,health
  endpoint:
    health:
      show-details: always #默认是never
info:
  app:
    version: 0.0.1-snapshop
# 配置断路器超时时间，默认是1000（1秒）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2001